package com.hermes.agent.ui.theme

import androidx.compose.ui.graphics.Color

// ── Midnight theme (black background / white text) ───────────────────
val MidnightBackground        = Color(0xFF000000)
val MidnightSurface           = Color(0xFF111111)
val MidnightSurfaceVariant    = Color(0xFF1A1A1A)
val MidnightOnBackground      = Color(0xFFFFFFFF)
val MidnightOnSurface         = Color(0xFFFFFFFF)
val MidnightOnSurfaceVariant  = Color(0xFFAAAAAA)
val MidnightPrimary           = Color(0xFFFFFFFF)
val MidnightOnPrimary         = Color(0xFF000000)
val MidnightPrimaryContainer  = Color(0xFF222222)
val MidnightOnPrimaryContainer= Color(0xFFFFFFFF)
val MidnightSecondary         = Color(0xFF888888)
val MidnightOnSecondary       = Color(0xFF000000)
val MidnightSecondaryContainer= Color(0xFF1A1A1A)
val MidnightError             = Color(0xFFFF4444)

val MidnightUserBubble        = Color(0xFF1A1A1A)
val MidnightUserBubbleText    = Color(0xFFFFFFFF)
val MidnightAssistantBubble   = Color(0xFF0D0D0D)
val MidnightAssistantBubbleText = Color(0xFFE0E0E0)

// ── Paper theme (white background / black text) ──────────────────────
val PaperBackground           = Color(0xFFFFFFFF)
val PaperSurface              = Color(0xFFF5F5F5)
val PaperSurfaceVariant       = Color(0xFFEEEEEE)
val PaperOnBackground         = Color(0xFF000000)
val PaperOnSurface            = Color(0xFF000000)
val PaperOnSurfaceVariant     = Color(0xFF666666)
val PaperPrimary              = Color(0xFF000000)
val PaperOnPrimary            = Color(0xFFFFFFFF)
val PaperPrimaryContainer     = Color(0xFFF0F0F0)
val PaperOnPrimaryContainer   = Color(0xFF000000)
val PaperSecondary            = Color(0xFF333333)
val PaperOnSecondary          = Color(0xFFFFFFFF)
val PaperSecondaryContainer   = Color(0xFFEEEEEE)
val PaperError                = Color(0xFFCC0000)

val PaperUserBubble           = Color(0xFF000000)
val PaperUserBubbleText       = Color(0xFFFFFFFF)
val PaperAssistantBubble      = Color(0xFFEEEEEE)
val PaperAssistantBubbleText  = Color(0xFF000000)

// ── Hermes Blue theme (electric blue background / white text) ────────
// Brand blue sourced from hermes-agent.nousresearch.com
val BlueBrandBackground           = Color(0xFF3300FF)
val BlueBrandSurface              = Color(0xFF2200DD)
val BlueBrandSurfaceVariant       = Color(0xFF1A00BB)
val BlueBrandOnBackground         = Color(0xFFFFFFFF)
val BlueBrandOnSurface            = Color(0xFFFFFFFF)
val BlueBrandOnSurfaceVariant     = Color(0xFFCCCCFF)
val BlueBrandPrimary              = Color(0xFFFFFFFF)
val BlueBrandOnPrimary            = Color(0xFF3300FF)
val BlueBrandPrimaryContainer     = Color(0xFF4411FF)
val BlueBrandOnPrimaryContainer   = Color(0xFFFFFFFF)
val BlueBrandSecondary            = Color(0xFFCCCCFF)
val BlueBrandOnSecondary          = Color(0xFF3300FF)
val BlueBrandSecondaryContainer   = Color(0xFF2200CC)
val BlueBrandError                = Color(0xFFFF6666)

val BlueBrandUserBubble           = Color(0xFF1A00BB)
val BlueBrandUserBubbleText       = Color(0xFFFFFFFF)
val BlueBrandAssistantBubble      = Color(0xFF2200CC)
val BlueBrandAssistantBubbleText  = Color(0xFFFFFFFF)

// ── Legacy palette (kept for any composables still referencing these) ─
val HermesPrimary              = Color(0xFF1E3A8A)
val HermesPrimaryDark          = Color(0xFF172554)
val HermesPrimaryContainer     = Color(0xFFDDE6FF)
val HermesOnPrimary            = Color(0xFFFFFFFF)
val HermesOnPrimaryContainer   = Color(0xFF001550)
val HermesAccent               = Color(0xFFF59E0B)
val HermesAccentDark           = Color(0xFFFFB951)
val HermesAccentContainer      = Color(0xFFFFE9C7)
val HermesOnAccent             = Color(0xFF1A1300)
val HermesBackground           = Color(0xFFF8FAFC)
val HermesSurface              = Color(0xFFFFFFFF)
val HermesSurfaceVariant       = Color(0xFFE7EAF0)
val HermesOnBackground         = Color(0xFF0F172A)
val HermesOnSurface            = Color(0xFF0F172A)
val HermesOnSurfaceVariant     = Color(0xFF44474F)
val HermesSuccess              = Color(0xFF16A34A)
val HermesWarning              = Color(0xFFEA580C)
val HermesError                = Color(0xFFDC2626)
val HermesPrimaryDarkMode      = Color(0xFFB1C5FF)
val HermesAccentDarkMode       = Color(0xFFFFB951)
val HermesBackgroundDark       = Color(0xFF0F172A)
val HermesSurfaceDark          = Color(0xFF1E293B)
val HermesOnBackgroundDark     = Color(0xFFE2E8F0)
val HermesOnSurfaceDark        = Color(0xFFE2E8F0)
val UserBubbleColor            = Color(0xFF1E3A8A)
val UserBubbleTextColor        = Color(0xFFFFFFFF)
val AssistantBubbleColor       = Color(0xFFF1F5F9)
val AssistantBubbleTextColor   = Color(0xFF0F172A)
val AssistantBubbleColorDark   = Color(0xFF334155)
val AssistantBubbleTextColorDark = Color(0xFFE2E8F0)
